[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;3D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;3C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;3A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;3B"
key = "Down"
mods = "Command"

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
